default:
  image: ubuntu:latest

stages:
  - install
  - build
  - test
  - check-codestyle

variables:
  SFML_DIR: "external/SFML"
  GTEST_DIR: "external/googletest"

install:
  stage: install
  script:
    - apt-get update -y
    - apt-get install -y git cmake make clang-format
    - rm -rf $SFML_DIR
    - rm -rf $GTEST_DIR
    - git submodule update --init --recursive
    - git submodule status
    - ls -la $SFML_DIR
    - ls -la $GTEST_DIR


check-codestyle:
  stage: check-codestyle
  script:
    - echo "Check codestyle..."
    - git ls-files *.{cpp,hpp} | xargs clang-format -i --verbose && git diff --exit-code
    - echo "Codestyle is fine"
